name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (headless on CI)
        env:
          CLIENT_URL: ${{ vars.CLIENT_URL }}
          API_URL_LOGIN: ${{ vars.API_URL_LOGIN }}
          API_URL_CREATE_ORDER: ${{ vars.API_URL_CREATE_ORDER }}
          LOGIN_PAGE_PRACTICE_URL: ${{ vars.LOGIN_PAGE_PRACTICE_URL }}
          CALENDAR_URL: ${{ vars.CALENDAR_URL }}
          LOCATOR_PRACTICE_URL: ${{ vars.LOCATOR_PRACTICE_URL }}
          AUTOMATION_PRACTICE_URL: ${{ vars.AUTOMATION_PRACTICE_URL }}
          UPLOAD_DOWNLOAD_URL: ${{ vars.UPLOAD_DOWNLOAD_URL }}
          PRODUCT_ID: ${{ vars.PRODUCT_ID }}
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
        run: npx playwright test

      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload traces
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: test-results/**/trace.zip
          retention-days: 7
